# Generated by Django 5.1.4 on 2025-04-24 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Предыстория',
                'verbose_name_plural': 'Предыстории',
            },
        ),
        migrations.CreateModel(
            name='SelectedFeatureOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Выбранный вариант особенности',
                'verbose_name_plural': 'Выбранные варианты особенностей',
            },
        ),
        migrations.CreateModel(
            name='SelectedOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SkillsProficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('skills_proficiency', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название черты')),
            ],
            options={
                'verbose_name': 'Черта характера',
                'verbose_name_plural': 'Черты характера',
            },
        ),
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название привязанности')),
                ('background', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonds', to='background.background', verbose_name='Предыстория')),
            ],
            options={
                'verbose_name': 'Привязанность',
                'verbose_name_plural': 'Привязанности',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название особенности')),
                ('description', models.TextField(verbose_name='Описание')),
                ('has_choice', models.BooleanField(default=False, verbose_name='Есть выбор')),
                ('background', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='background.background', verbose_name='Предыстория')),
            ],
            options={
                'verbose_name': 'Особенность предыстории',
                'verbose_name_plural': 'Особенности предыстории',
            },
        ),
        migrations.CreateModel(
            name='FeatureOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название варианта')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='background.feature', verbose_name='Особенность')),
            ],
            options={
                'verbose_name': 'Вариант особенности',
                'verbose_name_plural': 'Варианты особенностей',
            },
        ),
        migrations.CreateModel(
            name='Flaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название слабости')),
                ('background', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flaws', to='background.background', verbose_name='Предыстория')),
            ],
            options={
                'verbose_name': 'Слабость',
                'verbose_name_plural': 'Слабости',
            },
        ),
        migrations.CreateModel(
            name='Ideal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название идеала')),
                ('background', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideals', to='background.background', verbose_name='Предыстория')),
            ],
            options={
                'verbose_name': 'Идеал',
                'verbose_name_plural': 'Идеалы',
            },
        ),
    ]
