# Generated by Django 5.1.4 on 2025-04-24 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('background', '0001_initial'),
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedfeatureoption',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_feature_options', to='character.character', verbose_name='Персонаж'),
        ),
        migrations.AddField(
            model_name='selectedfeatureoption',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_options', to='background.feature', verbose_name='Особенность'),
        ),
        migrations.AddField(
            model_name='selectedfeatureoption',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_by', to='background.featureoption', verbose_name='Выбранный вариант'),
        ),
        migrations.AddField(
            model_name='selectedorigin',
            name='bond',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_by', to='background.bond', verbose_name='Выбранная привязанность'),
        ),
        migrations.AddField(
            model_name='selectedorigin',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_origin_options', to='character.character', verbose_name='Выбор предыстории'),
        ),
        migrations.AddField(
            model_name='selectedorigin',
            name='flaw',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_by', to='background.flaw', verbose_name='Выбранная слабость'),
        ),
        migrations.AddField(
            model_name='selectedorigin',
            name='ideal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_by', to='background.ideal', verbose_name='Выбранный идеал'),
        ),
        migrations.AddField(
            model_name='skillsproficiency',
            name='background_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_proficiencies', to='background.background'),
        ),
        migrations.AddField(
            model_name='trait',
            name='background',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traits', to='background.background', verbose_name='Предыстория'),
        ),
        migrations.AddField(
            model_name='selectedorigin',
            name='trait',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_by', to='background.trait', verbose_name='Выбранная черта'),
        ),
    ]
