services:
  backend:
    build: ./backend
    container_name: backend-container
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
  frontend:
    build: ./front
    container_name: frontend-container
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./front/nginx.conf:/etc/nginx/conf.d/default.conf


volumes:
  sqlite_data: