# Generated by Django 4.1.3 on 2023-03-01 07:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import dnd.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personality_traits', models.CharField(default='черты характера', max_length=1500)),
                ('ideals', models.CharField(default='идеалы', max_length=1500)),
                ('bonds', models.CharField(default='узы', max_length=1500)),
                ('flaws', models.CharField(default='недостатки', max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='BaseClassCh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champion_class', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DndSpell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=100, verbose_name='ссылка')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('lvl', models.CharField(max_length=15, verbose_name='уровень')),
                ('school', models.CharField(max_length=60, verbose_name='школа')),
                ('time_cast', models.CharField(max_length=200, verbose_name='время накладывания')),
                ('distance', models.CharField(max_length=100, verbose_name='дистанция')),
                ('components', models.CharField(max_length=400, verbose_name='компоненты')),
                ('timing', models.CharField(max_length=100, verbose_name='Длительность')),
                ('class_actor', models.CharField(blank=True, max_length=150, null=True, verbose_name='Классы')),
                ('architype', models.CharField(blank=True, max_length=200, null=True, verbose_name='Архетипы')),
                ('origin', models.CharField(blank=True, max_length=100, null=True, verbose_name='источник')),
                ('instruction', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Заклинание',
                'verbose_name_plural': 'Заклинания',
            },
        ),
        migrations.CreateModel(
            name='PreHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_history_choices', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProtectStateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protect_state_strength', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)])),
                ('protect_state_dexterity', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)])),
                ('protect_state_constitution', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)])),
                ('protect_state_intelligence', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)])),
                ('protect_state_wisdom', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)])),
                ('protect_state_charisma', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SkillStateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athletics', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('acrobatics', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('sleight_of_hand', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('stealth', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('arcana', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('history', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('investigation', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('nature', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('religion', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('animal_handling', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('insight', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('medicine', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('perception', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('survival', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('deception', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('intimidation', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('performance', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('persuasion', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='WeaponType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorldOutlook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('world_outlook', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('damage', models.CharField(blank=True, max_length=10, null=True)),
                ('damage_universal', models.CharField(blank=True, max_length=10, null=True)),
                ('price', models.CharField(blank=True, max_length=200, null=True)),
                ('damage_type', models.CharField(blank=True, max_length=200, null=True)),
                ('weight', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=3000, null=True)),
                ('properties', models.ManyToManyField(blank=True, default=dnd.models.Properties.default_name, to='dnd.properties')),
                ('type', models.ForeignKey(default=dnd.models.WeaponType.default_description, on_delete=django.db.models.deletion.PROTECT, to='dnd.weapontype')),
            ],
        ),
        migrations.CreateModel(
            name='Shield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dnd.weapontype')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_champion', models.CharField(blank=True, default='Безымянный герой', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('lvl', models.IntegerField(blank=True, default=1)),
                ('experience', models.IntegerField(blank=True, default=0)),
                ('ProficienciesAndLanguages', models.CharField(default='Список навыков и языков', max_length=4000)),
                ('max_hit', models.PositiveSmallIntegerField(default=0)),
                ('temp_hit', models.PositiveSmallIntegerField(default=0)),
                ('current_hit', models.PositiveSmallIntegerField(default=0)),
                ('strength', models.PositiveSmallIntegerField(blank=True, default=10, verbose_name='Сила')),
                ('dexterity', models.PositiveSmallIntegerField(blank=True, default=10, verbose_name='Ловкость')),
                ('constitution', models.PositiveSmallIntegerField(blank=True, default=10, verbose_name='Телосложение')),
                ('intelligence', models.PositiveSmallIntegerField(blank=True, default=10, verbose_name='Интиллект')),
                ('wisdom', models.PositiveSmallIntegerField(blank=True, default=10, verbose_name='Мудрость')),
                ('charisma', models.PositiveSmallIntegerField(blank=True, default=10, verbose_name='Харизма')),
                ('possession_bonus', models.PositiveSmallIntegerField(default=2, verbose_name='bonus')),
                ('inspiration', models.PositiveSmallIntegerField(default=0)),
                ('protection_class', models.PositiveSmallIntegerField(default=10, verbose_name='kz')),
                ('speed', models.PositiveSmallIntegerField(default=30, verbose_name='speed_ch')),
                ('account', models.ForeignKey(default='settings.AUTH_USER_MODEL', on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
                ('background', models.ForeignKey(default=dnd.models.BackgroundModel.default, on_delete=django.db.models.deletion.CASCADE, to='dnd.backgroundmodel')),
                ('champion_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dnd.baseclassch')),
                ('pre_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dnd.prehistorymodel')),
                ('protect_char_state', models.ForeignKey(default=dnd.models.ProtectStateModel.default_protect_state, on_delete=django.db.models.deletion.CASCADE, to='dnd.protectstatemodel')),
                ('race', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dnd.race')),
                ('skill_char_state', models.ForeignKey(default=dnd.models.SkillStateModel.default_skill_state, on_delete=django.db.models.deletion.CASCADE, to='dnd.skillstatemodel')),
                ('spells', models.ManyToManyField(blank=True, related_name='my_spells', to='dnd.dndspell')),
                ('weapon', models.ManyToManyField(blank=True, related_name='my_weapons', to='dnd.weapon')),
                ('world_outlook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dnd.worldoutlook')),
            ],
            options={
                'verbose_name': 'пресонаж',
                'verbose_name_plural': 'персонажи',
            },
        ),
    ]
