# Generated by Django 5.1.4 on 2025-04-24 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customracebackground',
            name='character',
        ),
        migrations.RemoveField(
            model_name='customracebackground',
            name='race_background',
        ),
        migrations.RemoveField(
            model_name='customsmallfeaturesrace',
            name='character',
        ),
        migrations.RemoveField(
            model_name='customsmallfeaturesrace',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='race',
            name='background',
        ),
        migrations.RemoveField(
            model_name='race',
            name='features',
        ),
    ]
