# Generated by Django 4.1.3 on 2023-01-19 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0002_alter_character_background'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrengthDModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res', models.CharField(blank=True, default='1', max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='character',
            name='background',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='dnd.backgroundmodel'),
        ),
        migrations.AddField(
            model_name='character',
            name='xxx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dnd.strengthdmodel'),
        ),
    ]
