# Generated by Django 4.1.3 on 2023-06-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0002_auto_20230628_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='classchampion',
            name='possession_bonus',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
