# Generated by Django 5.1.4 on 2025-04-24 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0002_remove_customracebackground_character_and_more'),
        ('race', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='race.race'),
        ),
        migrations.RemoveField(
            model_name='subrace',
            name='race',
        ),
        migrations.RemoveField(
            model_name='subrace',
            name='background',
        ),
        migrations.RemoveField(
            model_name='subrace',
            name='features',
        ),
        migrations.AlterField(
            model_name='character',
            name='sub_race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='race.subrace'),
        ),
        migrations.DeleteModel(
            name='CustomRaceBackground',
        ),
        migrations.DeleteModel(
            name='CustomSmallFeaturesRace',
        ),
        migrations.DeleteModel(
            name='Race',
        ),
        migrations.DeleteModel(
            name='RaceBackground',
        ),
        migrations.DeleteModel(
            name='SmallFeaturesRace',
        ),
        migrations.DeleteModel(
            name='SubRace',
        ),
    ]
