# Generated by Django 5.1.4 on 2025-04-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0003_auto_20250403_1401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='magicitems',
            options={'ordering': ['item']},
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='put_on',
            field=models.BooleanField(default=False),
        ),
    ]
