# Generated by Django 5.1.4 on 2025-01-22 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0003_auto_20250121_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='protect_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dnd.protectstatemodel'),
        ),
        migrations.AlterField(
            model_name='character',
            name='skill_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dnd.skillstatemodel'),
        ),
    ]
