# Generated by Django 5.1.4 on 2025-03-04 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0003_auto_20250302_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='customability',
            name='hide_custom',
            field=models.BooleanField(default=True),
        ),
    ]
