# Generated by Django 4.1.3 on 2023-02-27 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0003_shield'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='shield',
            name='shield',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shields', to='dnd.task'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='weapon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weapons', to='dnd.task'),
        ),
    ]
