# Generated by Django 4.1.3 on 2023-01-19 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0003_strengthdmodel_alter_character_background_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='background',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='dnd.backgroundmodel'),
        ),
        migrations.AlterField(
            model_name='character',
            name='xxx',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dnd.strengthdmodel'),
        ),
    ]
