# Generated by Django 4.1.3 on 2023-01-19 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0004_alter_character_background_alter_character_xxx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strengthdmodel',
            name='res',
        ),
        migrations.AddField(
            model_name='strengthdmodel',
            name='base_value',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='strengthdmodel',
            name='state_defender',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='strengthdmodel',
            name='state_skill',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='background',
            field=models.ForeignKey(default=19, on_delete=django.db.models.deletion.CASCADE, to='dnd.backgroundmodel'),
        ),
        migrations.AlterField(
            model_name='character',
            name='xxx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd.strengthdmodel'),
        ),
        migrations.AlterField(
            model_name='race',
            name='race',
            field=models.SmallIntegerField(blank=True, max_length=100),
        ),
    ]
