# Generated by Django 4.1.3 on 2023-10-21 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0004_classchampion_available_gear_classchampion_dice_hit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubclassChampion',
            fields=[
                ('classchampion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dnd.classchampion')),
                ('subclass_name', models.CharField(max_length=100)),
            ],
            bases=('dnd.classchampion',),
        ),
        migrations.AlterModelOptions(
            name='spell',
            options={'ordering': ['name'], 'verbose_name': 'Заклинание', 'verbose_name_plural': 'Заклинания'},
        ),
        migrations.AlterField(
            model_name='spelllevel',
            name='known_conspiracies',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Известные заговоры'),
        ),
        migrations.AlterField(
            model_name='spelllevel',
            name='known_spell',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Известные заклинания'),
        ),
        migrations.AlterField(
            model_name='spelllevel',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='spelllevel',
            name='spell_slots',
            field=models.JSONField(blank=True, null=True, verbose_name='Слоты заклинаний'),
        ),
    ]
