# Generated by Django 5.1.4 on 2025-01-23 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0005_alter_character_protect_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='protect_state',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dnd.protectstatemodel'),
        ),
        migrations.AlterField(
            model_name='character',
            name='skill_state',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dnd.skillstatemodel'),
        ),
    ]
