# Generated by Django 5.1.4 on 2025-01-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0007_alter_character_protect_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='race',
        ),
        migrations.AddField(
            model_name='baseclass',
            name='class_skills',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Классовые навыки'),
        ),
        migrations.AddField(
            model_name='baseclass',
            name='hit_at_first_level',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Хиты на первом уровне'),
        ),
        migrations.AddField(
            model_name='baseclass',
            name='hit_at_next_level',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Хиты на следующих уровнях'),
        ),
        migrations.AddField(
            model_name='baseclass',
            name='possession_armor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Владение доспехами'),
        ),
        migrations.AddField(
            model_name='baseclass',
            name='possession_instrument',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Владение инструментами'),
        ),
        migrations.AddField(
            model_name='baseclass',
            name='possession_weapon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Владение оружием'),
        ),
        migrations.AddField(
            model_name='baseclass',
            name='saving_throws',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Спасброски'),
        ),
        migrations.DeleteModel(
            name='Race',
        ),
    ]
