# Generated by Django 4.1.3 on 2023-10-24 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0007_rename_subclasschampion_archetypechampion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='spell',
            name='archetype',
        ),
        migrations.DeleteModel(
            name='ArchetypeChampion',
        ),
        migrations.AddField(
            model_name='archetype',
            name='additional_spells',
            field=models.ManyToManyField(to='dnd.spell'),
        ),
        migrations.AddField(
            model_name='archetype',
            name='character_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd.classchampion'),
        ),
    ]
