# Generated by Django 5.1.4 on 2025-01-24 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0008_remove_character_race_baseclass_class_skills_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureRace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название особенности')),
                ('description', models.TextField(verbose_name='Описание особенности')),
            ],
            options={
                'verbose_name': 'Особенность',
                'verbose_name_plural': 'Особенности',
            },
        ),
        migrations.CreateModel(
            name='OriginRace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название особенности')),
                ('description', models.TextField(verbose_name='Описание особенности')),
            ],
            options={
                'verbose_name': 'Основная особенность',
                'verbose_name_plural': 'основные особенности',
            },
        ),
        migrations.RemoveField(
            model_name='character',
            name='my_origin',
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название расы')),
                ('description', models.TextField(verbose_name='Описание')),
                ('features', models.ManyToManyField(related_name='races_features', to='dnd.featurerace', verbose_name='Особенности')),
                ('origin', models.ManyToManyField(related_name='races_origin', to='dnd.originrace', verbose_name='История рассы')),
            ],
            options={
                'verbose_name': 'Раса',
                'verbose_name_plural': 'Расы',
            },
        ),
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dnd.race'),
        ),
        migrations.CreateModel(
            name='SubRace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название подвида')),
                ('description', models.TextField(verbose_name='Описание')),
                ('features', models.ManyToManyField(related_name='subraces_features', to='dnd.featurerace', verbose_name='Особенности подвида')),
                ('origin', models.ManyToManyField(related_name='subraces_origin', to='dnd.originrace', verbose_name='История подвида')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subraces', to='dnd.race', verbose_name='Основная раса')),
            ],
            options={
                'verbose_name': 'Подвид',
                'verbose_name_plural': 'Подвиды',
            },
        ),
        migrations.DeleteModel(
            name='Origin',
        ),
    ]
