# Generated by Django 4.1.3 on 2023-01-24 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0009_album_alter_character_background_alter_character_xxx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='track',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='track',
            name='album',
        ),
        migrations.RemoveField(
            model_name='character',
            name='xxx',
        ),
        migrations.AlterField(
            model_name='character',
            name='background',
            field=models.ForeignKey(default=236, on_delete=django.db.models.deletion.CASCADE, related_name='bac', to='dnd.backgroundmodel'),
        ),
        migrations.AlterField(
            model_name='race',
            name='race',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='StrengthDModel',
        ),
        migrations.DeleteModel(
            name='Track',
        ),
    ]
