# Generated by Django 5.1.4 on 2025-01-24 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0009_featurerace_originrace_remove_character_my_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='sub_race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dnd.subrace'),
        ),
    ]
