# Generated by Django 4.1.3 on 2023-04-22 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0010_auto_20230421_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagicItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homebrew', models.BooleanField(default=False)),
                ('price', models.CharField(blank=True, default='-', max_length=200, null=True)),
                ('source', models.CharField(blank=True, default='-', max_length=200, null=True)),
                ('customization', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, default='-', max_length=3000, null=True)),
                ('detailCustamization', models.CharField(blank=True, default='-', max_length=200, null=True)),
                ('detailType', models.CharField(blank=True, default='-', max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ring',
            name='item',
        ),
        migrations.RemoveField(
            model_name='scroll',
            name='item',
        ),
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.DeleteModel(
            name='Potion',
        ),
        migrations.DeleteModel(
            name='Ring',
        ),
        migrations.DeleteModel(
            name='Scroll',
        ),
        migrations.AddField(
            model_name='magicitems',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='magic_item', to='dnd.item'),
        ),
        migrations.AddField(
            model_name='magicitems',
            name='sub_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='magic_item_type', to='dnd.subtype'),
        ),
    ]
