# Generated by Django 5.1.4 on 2025-01-26 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0010_character_sub_race'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_description', models.TextField(blank=True, null=True, verbose_name='Пользовательское описание')),
                ('hide_original', models.BooleanField(default=False, verbose_name='Скрыть оригинальный текст')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_features', to='dnd.character')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_features', to='dnd.featurerace')),
            ],
            options={
                'verbose_name': 'Пользовательская особенность',
                'verbose_name_plural': 'Пользовательские особенности',
            },
        ),
        migrations.CreateModel(
            name='CustomOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_description', models.TextField(blank=True, null=True, verbose_name='Пользовательское описание')),
                ('hide_original', models.BooleanField(default=False, verbose_name='Скрыть оригинальный текст')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_origins', to='dnd.character')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_origins', to='dnd.originrace')),
            ],
            options={
                'verbose_name': 'Пользовательская основная особенность',
                'verbose_name_plural': 'Пользовательские основные особенности',
            },
        ),
    ]
