# Generated by Django 4.1.3 on 2023-01-24 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dnd', '0010_alter_track_unique_together_remove_track_album_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='account',
            field=models.ForeignKey(default='settings.AUTH_USER_MODEL', on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='character',
            name='background',
            field=models.ForeignKey(default=246, on_delete=django.db.models.deletion.CASCADE, related_name='bac', to='dnd.backgroundmodel'),
        ),
    ]
