# Generated by Django 4.1.3 on 2023-01-25 04:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import dnd.models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0011_alter_character_account_alter_character_background'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtectStateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protect_state_strength', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)])),
                ('protect_state_dexterity', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)])),
                ('protect_state_constitution', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)])),
                ('protect_state_intelligence', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)])),
                ('protect_state_wisdom', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)])),
                ('protect_state_charisma', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='SkillStateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athletics', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('acrobatics', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('sleight_of_hand', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('stealth', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('arcana', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('history', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('investigation', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('nature', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('religion', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('animal_handling', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('insight', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('medicine', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('perception', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('survival', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('deception', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('intimidation', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('performance', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('persuasion', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.AlterField(
            model_name='backgroundmodel',
            name='bonds',
            field=models.CharField(default='узы', max_length=1500),
        ),
        migrations.AlterField(
            model_name='backgroundmodel',
            name='flaws',
            field=models.CharField(default='недостатки', max_length=1500),
        ),
        migrations.AlterField(
            model_name='backgroundmodel',
            name='ideals',
            field=models.CharField(default='идеалы', max_length=1500),
        ),
        migrations.AlterField(
            model_name='backgroundmodel',
            name='personality_traits',
            field=models.CharField(default='черты характера', max_length=1500),
        ),
        migrations.AlterField(
            model_name='character',
            name='background',
            field=models.ForeignKey(default=dnd.models.BackgroundModel.default, on_delete=django.db.models.deletion.CASCADE, to='dnd.backgroundmodel'),
        ),
        migrations.AlterField(
            model_name='character',
            name='pre_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dnd.prehistorymodel'),
        ),
        migrations.AddField(
            model_name='character',
            name='protect_char_state',
            field=models.ForeignKey(default=dnd.models.ProtectStateModel.default_protect_state, on_delete=django.db.models.deletion.CASCADE, to='dnd.protectstatemodel'),
        ),
        migrations.AddField(
            model_name='character',
            name='skill_char_state',
            field=models.ForeignKey(default=dnd.models.SkillStateModel.default_skill_state, on_delete=django.db.models.deletion.CASCADE, to='dnd.skillstatemodel'),
        ),
    ]
