# Generated by Django 5.1.4 on 2025-04-09 16:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0012_auto_20250409_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spellslotlevel',
            name='level',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
    ]
