# Generated by Django 5.1.4 on 2025-01-26 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0012_rename_customfeature_customracefeature'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomRaceFeature',
            new_name='CustomFeature',
        ),
        migrations.AlterModelOptions(
            name='featurerace',
            options={'verbose_name': 'Общие особенности расы', 'verbose_name_plural': 'Общие особенности расы'},
        ),
        migrations.AlterField(
            model_name='subrace',
            name='features',
            field=models.ManyToManyField(related_name='subraces_features_history_race_backgrounds', to='dnd.featurerace', verbose_name='Особенности подвида'),
        ),
        migrations.AlterField(
            model_name='subrace',
            name='origin',
            field=models.ManyToManyField(related_name='subraces_history_race_backgrounds', to='dnd.originrace', verbose_name='История подвида'),
        ),
        migrations.RenameModel(
            old_name='OriginRace',
            new_name='RaceBackground',
        ),
        migrations.CreateModel(
            name='CustomRaceBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_description', models.TextField(blank=True, null=True, verbose_name='Пользовательское описание')),
                ('hide_original', models.BooleanField(default=False, verbose_name='Скрыть оригинальный текст')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_history_race_backgrounds', to='dnd.character')),
                ('race_background', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_history_race_backgrounds', to='dnd.racebackground')),
            ],
            options={
                'verbose_name': 'Пользовательская основная особенность',
                'verbose_name_plural': 'Пользовательские основные особенности',
            },
        ),
        migrations.DeleteModel(
            name='CustomOrigin',
        ),
    ]
