# Generated by Django 4.1.3 on 2023-10-30 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0013_remove_classchampion_spell_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='spelllevel',
            name='character_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dnd.classchampion'),
        ),
    ]
