# Generated by Django 5.1.4 on 2025-01-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0013_rename_customracefeature_customfeature_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customfeature',
            options={'verbose_name': 'Пользовательская общая особенность расы', 'verbose_name_plural': 'Пользовательские общие особенности рас'},
        ),
        migrations.AlterModelOptions(
            name='customracebackground',
            options={'verbose_name': 'Пользовательская историческая особенность расы', 'verbose_name_plural': 'Пользовательские исторические особенности рас'},
        ),
        migrations.AlterModelOptions(
            name='racebackground',
            options={'verbose_name': 'Историческая особенность расы', 'verbose_name_plural': 'Исторические особенности рас'},
        ),
        migrations.RemoveField(
            model_name='race',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='subrace',
            name='origin',
        ),
        migrations.AddField(
            model_name='race',
            name='background',
            field=models.ManyToManyField(related_name='races_backgrounds', to='dnd.racebackground', verbose_name='История рассы'),
        ),
        migrations.AddField(
            model_name='subrace',
            name='background',
            field=models.ManyToManyField(related_name='sub_races_backgrounds', to='dnd.racebackground', verbose_name='История подвида'),
        ),
        migrations.AlterField(
            model_name='subrace',
            name='features',
            field=models.ManyToManyField(related_name='sub_races_features_race', to='dnd.featurerace', verbose_name='Особенности подвида'),
        ),
    ]
