# Generated by Django 4.1.3 on 2023-11-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0014_spelllevel_character_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worldoutlook',
            old_name='world_outlook',
            new_name='name',
        ),
        migrations.AddField(
            model_name='worldoutlook',
            name='description',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
