# Generated by Django 5.1.4 on 2025-01-27 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0014_alter_customfeature_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomFeature',
            new_name='CustomFeatureRace',
        ),
    ]
