# Generated by Django 5.1.4 on 2025-01-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0015_rename_customfeature_customfeaturerace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Описание способности'),
        ),
    ]
