# Generated by Django 5.1.4 on 2025-01-27 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0016_alter_ability_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_description', models.TextField(blank=True, null=True)),
                ('hide_original', models.BooleanField(default=False)),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_attributes_class_ability', to='dnd.ability')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_attributes_class_character', to='dnd.character')),
            ],
            options={
                'verbose_name': 'Пользовательская особенность класса',
                'verbose_name_plural': 'Пользовательские особенности класса',
            },
        ),
    ]
