# Generated by Django 5.1.4 on 2025-02-04 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0017_customability'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archetypelevel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='customability',
            options={},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='archetypelevel',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='archetypespecificcolumnvalue',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='level',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='specificcolumnvalue',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='ability',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ability',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='dnd.level'),
        ),
        migrations.AlterField(
            model_name='ability',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='archetype',
            name='character_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archetypes', to='dnd.baseclass'),
        ),
        migrations.AlterField(
            model_name='archetype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='archetype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='archetypeability',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='archetypeability',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archetype_abilities', to='dnd.archetypelevel'),
        ),
        migrations.AlterField(
            model_name='archetypeability',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='archetypelevel',
            name='archetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archetype_levels', to='dnd.archetype'),
        ),
        migrations.AlterField(
            model_name='archetypelevel',
            name='level',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='archetypespecificcolumn',
            name='archetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archetype_specific_columns', to='dnd.archetype'),
        ),
        migrations.AlterField(
            model_name='archetypespecificcolumn',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='archetypespecificcolumnvalue',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specific_column_values', to='dnd.archetypelevel'),
        ),
        migrations.AlterField(
            model_name='archetypespecificcolumnvalue',
            name='specific_column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='dnd.archetypespecificcolumn'),
        ),
        migrations.AlterField(
            model_name='archetypespecificcolumnvalue',
            name='value',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='customability',
            name='ability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_versions', to='dnd.ability'),
        ),
        migrations.AlterField(
            model_name='customability',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_abilities', to='dnd.character'),
        ),
        migrations.AlterField(
            model_name='level',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='dnd.baseclass'),
        ),
        migrations.AlterField(
            model_name='level',
            name='level',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='level',
            name='proficiency_bonus',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='specificcolumn',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specific_columns', to='dnd.baseclass'),
        ),
        migrations.AlterField(
            model_name='specificcolumn',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='specificcolumnvalue',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specific_column_values', to='dnd.level'),
        ),
        migrations.AlterField(
            model_name='specificcolumnvalue',
            name='specific_column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='dnd.specificcolumn'),
        ),
        migrations.AlterField(
            model_name='specificcolumnvalue',
            name='value',
            field=models.JSONField(),
        ),
        migrations.CreateModel(
            name='ArchetypeCustomAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_description', models.TextField(blank=True, null=True)),
                ('hide_original', models.BooleanField(default=False)),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archetype_custom_versions', to='dnd.ability')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archetype_custom_abilities', to='dnd.character')),
            ],
        ),
    ]
