# Generated by Django 5.1.4 on 2025-02-04 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0018_alter_archetypelevel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archetypecustomability',
            name='ability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archetype_custom_versions', to='dnd.archetypeability'),
        ),
    ]
