# Generated by Django 5.1.4 on 2025-02-04 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0019_alter_archetypecustomability_ability'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_description', models.TextField(blank=True, null=True, verbose_name='Пользовательское описание')),
                ('hide_original', models.BooleanField(default=False, verbose_name='Скрыть оригинальный текст')),
            ],
        ),
        migrations.DeleteModel(
            name='Ideal',
        ),
        migrations.RemoveField(
            model_name='backgroundmodel',
            name='bonds',
        ),
        migrations.RemoveField(
            model_name='backgroundmodel',
            name='flaws',
        ),
        migrations.RemoveField(
            model_name='backgroundmodel',
            name='ideals',
        ),
        migrations.RemoveField(
            model_name='backgroundmodel',
            name='personality_traits',
        ),
        migrations.AddField(
            model_name='backgroundmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backgroundmodel',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dnd.backgroundmodel'),
        ),
        migrations.AddField(
            model_name='backgroundmodel',
            name='specifications',
            field=models.ManyToManyField(to='dnd.backgroundspecification'),
        ),
        migrations.AddField(
            model_name='custombackground',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='background_specification_custom', to='dnd.character'),
        ),
        migrations.AddField(
            model_name='custombackground',
            name='race_background',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='background_specification_custom', to='dnd.backgroundspecification'),
        ),
    ]
