# Generated by Django 5.1.4 on 2025-02-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0020_backgroundspecification_custombackground_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundmodel',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
