# Generated by Django 5.1.4 on 2025-02-05 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0021_alter_backgroundmodel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineamentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomLineament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_description', models.TextField(blank=True, null=True, verbose_name='Пользовательское описание')),
                ('hide_original', models.BooleanField(default=False, verbose_name='Скрыть оригинальный текст')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineament_custom', to='dnd.character')),
                ('lineament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineament_custom', to='dnd.lineamentmodel')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='lineament',
            field=models.ManyToManyField(to='dnd.lineamentmodel', verbose_name='Черты'),
        ),
    ]
