# Generated by Django 5.1.4 on 2025-04-24 04:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dnd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagicSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Школа заклинаний',
                'verbose_name_plural': 'Школы заклинаний',
            },
        ),
        migrations.CreateModel(
            name='SpellSlotLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)])),
                ('count', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(0)])),
                ('used', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Уровень ячеек заклинаний',
                'verbose_name_plural': 'Уровни ячеек заклинаний',
            },
        ),
        migrations.CreateModel(
            name='CharacterSpellSlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spell_slots', to='dnd.character', verbose_name='Персонаж')),
            ],
            options={
                'verbose_name': 'Ячейки заклинаний персонажа',
                'verbose_name_plural': 'Ячейки заклинаний персонажей',
            },
        ),
        migrations.CreateModel(
            name='CharacterSpellSlotLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spells', models.JSONField(blank=True, default=list, null=True)),
                ('character_spell_slots', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_levels', to='spellbook.characterspellslots', verbose_name='Ячейки заклинаний персонажа')),
                ('spell_slot_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_slots', to='spellbook.spellslotlevel', verbose_name='Уровень ячейки')),
            ],
            options={
                'verbose_name': 'Уровень ячеек заклинаний персонажа',
                'verbose_name_plural': 'Уровни ячеек заклинаний персонажей',
            },
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=100, verbose_name='ссылка')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('time_cast', models.CharField(max_length=200, verbose_name='время накладывания')),
                ('distance', models.CharField(max_length=100, verbose_name='дистанция')),
                ('components', models.CharField(max_length=400, verbose_name='компоненты')),
                ('timing', models.CharField(max_length=100, verbose_name='Длительность')),
                ('origin', models.CharField(blank=True, max_length=100, null=True, verbose_name='источник')),
                ('instruction', models.TextField(verbose_name='описание')),
                ('level', models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(9)])),
                ('archetype', models.ManyToManyField(blank=True, related_name='archetype_spells', to='dnd.archetype')),
                ('class_actor', models.ManyToManyField(blank=True, related_name='class_spells', to='dnd.baseclass')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spellbook.magicschool')),
            ],
            options={
                'verbose_name': 'Заклинание',
                'verbose_name_plural': 'Заклинания',
                'ordering': ['level', 'name'],
            },
        ),
        migrations.AddField(
            model_name='characterspellslots',
            name='levels',
            field=models.ManyToManyField(through='spellbook.CharacterSpellSlotLevel', to='spellbook.spellslotlevel', verbose_name='Уровни ячеек'),
        ),
    ]
