# Generated by Django 5.1.4 on 2025-04-24 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название особенности')),
                ('description', models.TextField(verbose_name='Описание особенности')),
            ],
            options={
                'verbose_name': 'Историческая особенность расы',
                'verbose_name_plural': 'Исторические особенности рас',
            },
        ),
        migrations.CreateModel(
            name='SmallFeaturesRace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название особенности')),
                ('description', models.TextField(verbose_name='Описание особенности')),
            ],
            options={
                'verbose_name': 'Общие особенности расы',
                'verbose_name_plural': 'Общие особенности расы',
            },
        ),
        migrations.CreateModel(
            name='CustomRaceBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_description', models.TextField(blank=True, null=True, verbose_name='Пользовательское описание')),
                ('hide_original', models.BooleanField(default=False)),
                ('hide_custom', models.BooleanField(default=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_history_race_backgrounds', to='character.character')),
                ('race_background', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_history_race_backgrounds', to='race.racebackground')),
            ],
            options={
                'verbose_name': 'Пользовательская историческая особенность расы',
                'verbose_name_plural': 'Пользовательские исторические особенности рас',
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название расы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('background', models.ManyToManyField(blank=True, related_name='race', to='race.racebackground', verbose_name='История расы')),
                ('features', models.ManyToManyField(blank=True, related_name='race', to='race.smallfeaturesrace', verbose_name='Особенности')),
            ],
            options={
                'verbose_name': 'Раса',
                'verbose_name_plural': 'Расы',
            },
        ),
        migrations.CreateModel(
            name='CustomSmallFeaturesRace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_description', models.TextField(blank=True, null=True, verbose_name='Пользовательское описание')),
                ('hide_original', models.BooleanField(default=False)),
                ('hide_custom', models.BooleanField(default=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_features', to='character.character')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_features', to='race.smallfeaturesrace')),
            ],
            options={
                'verbose_name': 'Пользовательская общая особенность расы',
                'verbose_name_plural': 'Пользовательские общие особенности рас',
            },
        ),
        migrations.CreateModel(
            name='SubRace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название подвида')),
                ('description', models.TextField(verbose_name='Описание')),
                ('background', models.ManyToManyField(related_name='sub_races_backgrounds', to='race.racebackground', verbose_name='История подвида')),
                ('features', models.ManyToManyField(related_name='sub_race', to='race.smallfeaturesrace', verbose_name='Особенности подвида')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_race', to='race.race', verbose_name='Основная раса')),
            ],
            options={
                'verbose_name': 'Подвид',
                'verbose_name_plural': 'Подвиды',
            },
        ),
    ]
