# Generated by Django 5.1.4 on 2025-04-24 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BaseClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название класса')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание класса')),
                ('hit_dice', models.CharField(blank=True, max_length=10, null=True, verbose_name='Кость хитов')),
                ('hit_at_first_level', models.CharField(blank=True, max_length=10, null=True, verbose_name='Хиты на первом уровне')),
                ('hit_at_next_level', models.CharField(blank=True, max_length=100, null=True, verbose_name='Хиты на следующих уровнях')),
                ('possession_armor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Владение доспехами')),
                ('possession_weapon', models.CharField(blank=True, max_length=100, null=True, verbose_name='Владение оружием')),
                ('possession_instrument', models.CharField(blank=True, max_length=100, null=True, verbose_name='Владение инструментами')),
                ('saving_throws', models.CharField(blank=True, max_length=100, null=True, verbose_name='Спасброски')),
                ('class_skills', models.CharField(blank=True, max_length=100, null=True, verbose_name='Классовые навыки')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField()),
                ('proficiency_bonus', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MiniDescriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название небольшого описания класса')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='SpecificColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='SpellSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slots', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Archetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archetypes', to='champion_class.baseclass')),
            ],
        ),
        migrations.CreateModel(
            name='CustomAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_description', models.TextField(blank=True, null=True)),
                ('hide_original', models.BooleanField(default=False)),
                ('hide_custom', models.BooleanField(default=True)),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_versions', to='champion_class.ability')),
            ],
        ),
    ]
