# Generated by Django 5.1.4 on 2025-04-24 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('champion_class', '0001_initial'),
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customability',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_abilities', to='character.character'),
        ),
        migrations.AddField(
            model_name='level',
            name='archetype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='champion_class.archetype'),
        ),
        migrations.AddField(
            model_name='level',
            name='class_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='champion_class.baseclass'),
        ),
        migrations.AddField(
            model_name='ability',
            name='level_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='champion_class.level'),
        ),
        migrations.AddField(
            model_name='baseclass',
            name='mini_descriptions',
            field=models.ManyToManyField(related_name='mini_descriptions', to='champion_class.minidescriptions'),
        ),
        migrations.AddField(
            model_name='specificcolumn',
            name='archetype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specific_columns', to='champion_class.archetype'),
        ),
        migrations.AddField(
            model_name='specificcolumn',
            name='class_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specific_columns', to='champion_class.baseclass'),
        ),
        migrations.AddField(
            model_name='spellslot',
            name='archetype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spell_slots', to='champion_class.archetype'),
        ),
        migrations.AddField(
            model_name='spellslot',
            name='class_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spell_slots', to='champion_class.baseclass'),
        ),
    ]
