# Generated by Django 5.1.4 on 2025-04-24 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('character', '0001_initial'),
        ('lineaments', '0001_initial'),
        ('race', '0001_initial'),
        ('worldoutlook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='lineament',
            field=models.ManyToManyField(blank=True, to='lineaments.lineamentmodel', verbose_name='Черты'),
        ),
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='race.race'),
        ),
        migrations.AddField(
            model_name='character',
            name='sub_race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='race.subrace'),
        ),
        migrations.AddField(
            model_name='character',
            name='world_outlook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='worldoutlook.worldoutlook'),
        ),
        migrations.AddField(
            model_name='character',
            name='protect_state',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='character.protectstatemodel', verbose_name='Спасброски'),
        ),
        migrations.AddField(
            model_name='character',
            name='skills',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='character.skills', verbose_name='Характеристики'),
        ),
        migrations.AddField(
            model_name='character',
            name='skill_state',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='character.skillstatemodel', verbose_name='Владения навыками'),
        ),
    ]
