# Generated by Django 4.1.3 on 2023-10-21 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0005_subclasschampion_alter_spell_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subclasschampion',
            name='main_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subclass', to='dnd.classchampion'),
        ),
    ]
