# Generated by Django 4.1.3 on 2023-10-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0008_archetype_remove_spell_archetype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archetype',
            name='additional_spells',
        ),
        migrations.AddField(
            model_name='spell',
            name='archetype',
            field=models.ManyToManyField(blank=True, related_name='archetype_spells', to='dnd.archetype'),
        ),
    ]
