# Generated by Django 4.1.3 on 2023-10-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0010_auto_20231024_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classchampion',
            name='spell_slots',
            field=models.ManyToManyField(blank=True, null=True, to='dnd.spelllevel', verbose_name='Доступные ячейки'),
        ),
    ]
