# Generated by Django 4.1.3 on 2023-10-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0011_alter_classchampion_spell_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classchampion',
            name='spell_slots',
            field=models.ManyToManyField(blank=True, to='dnd.spelllevel', verbose_name='Доступные ячейки'),
        ),
    ]
