# Generated by Django 4.1.3 on 2023-10-30 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0012_alter_classchampion_spell_slots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classchampion',
            name='spell_slots',
        ),
    ]
