# Generated by Django 4.1.3 on 2023-11-01 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0016_auto_20231101_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondaryModel3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_info', models.CharField(default='33333', max_length=100)),
                ('primary_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd.race')),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryModel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_info', models.CharField(default='fdfd', max_length=100)),
                ('info', models.CharField(default='2222', max_length=100)),
                ('primary_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd.race')),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryModel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_info', models.IntegerField(default=100)),
                ('primary_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd.race')),
            ],
        ),
    ]
