# Generated by Django 4.1.3 on 2023-11-02 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0017_secondarymodel3_secondarymodel2_secondarymodel1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ideal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100)),
                ('ideal_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin_choice', to='dnd.ideal')),
                ('ideals', models.ManyToManyField(related_name='origins', to='dnd.ideal')),
            ],
        ),
        migrations.RemoveField(
            model_name='character',
            name='pre_history',
        ),
        migrations.DeleteModel(
            name='PreHistoryModel',
        ),
        migrations.AddField(
            model_name='character',
            name='my_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dnd.origin'),
        ),
    ]
