# Generated by Django 5.1.4 on 2025-01-20 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0018_ideal_origin_remove_character_pre_history_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название класса')),
                ('hit_dice', models.CharField(default='1d8', max_length=10, verbose_name='Кость здоровья')),
                ('primary_abilities', models.CharField(max_length=200, verbose_name='Основные характеристики')),
                ('saving_throws', models.CharField(max_length=200, verbose_name='Спасброски')),
                ('proficiencies', models.TextField(verbose_name='Владения')),
                ('skill_options', models.TextField(max_length=100, verbose_name='Доступные навыки')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
            },
        ),
        migrations.RemoveField(
            model_name='origin',
            name='ideal_choice',
        ),
        migrations.CreateModel(
            name='ClassFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(verbose_name='Уровень')),
                ('name', models.CharField(max_length=200, verbose_name='Название умения')),
                ('description', models.TextField(verbose_name='Описание')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='dnd.baseclass', verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Умение класса',
                'verbose_name_plural': 'Умения классов',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='SpellSlotProgression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(verbose_name='Уровень')),
                ('slots_level_0', models.PositiveIntegerField(default=0, verbose_name='Ячейки заговоров')),
                ('slots_level_1', models.PositiveIntegerField(default=0, verbose_name='Ячейки 1 уровня')),
                ('slots_level_2', models.PositiveIntegerField(default=0, verbose_name='Ячейки 2 уровня')),
                ('slots_level_3', models.PositiveIntegerField(default=0, verbose_name='Ячейки 3 уровня')),
                ('slots_level_4', models.PositiveIntegerField(default=0, verbose_name='Ячейки 4 уровня')),
                ('slots_level_5', models.PositiveIntegerField(default=0, verbose_name='Ячейки 5 уровня')),
                ('slots_level_6', models.PositiveIntegerField(default=0, verbose_name='Ячейки 6 уровня')),
                ('slots_level_7', models.PositiveIntegerField(default=0, verbose_name='Ячейки 7 уровня')),
                ('slots_level_8', models.PositiveIntegerField(default=0, verbose_name='Ячейки 8 уровня')),
                ('slots_level_9', models.PositiveIntegerField(default=0, verbose_name='Ячейки 9 уровня')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spell_slots', to='dnd.baseclass', verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Прогрессия магических ячеек',
                'verbose_name_plural': 'Прогрессии магических ячеек',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='Subclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название подкласса')),
                ('description', models.TextField(verbose_name='Описание подкласса')),
                ('parent_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subclasses', to='dnd.baseclass', verbose_name='Основной класс')),
            ],
            options={
                'verbose_name': 'Подкласс',
                'verbose_name_plural': 'Подклассы',
            },
        ),
    ]
