# Generated by Django 5.1.4 on 2025-01-20 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0019_baseclass_remove_origin_ideal_choice_classfeature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='champion_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dnd.baseclass'),
        ),
    ]
