# Generated by Django 5.1.4 on 2025-01-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0020_alter_character_champion_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spellslotprogression',
            name='slots_level_0',
        ),
        migrations.AddField(
            model_name='baseclass',
            name='has_spell_slots',
            field=models.BooleanField(default=False, verbose_name='Есть ли ячейки заклинаний'),
        ),
    ]
