# Generated by Django 5.1.4 on 2025-01-21 17:25

import django.db.models.deletion
import dnd.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0023_auto_20250121_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='background',
            field=models.OneToOneField(
                default=dnd.models.BackgroundModel.default_background_state(), on_delete=django.db.models.deletion.CASCADE, to='dnd.backgroundmodel'),
        ),
    ]
