# Generated by Django 5.1.4 on 2025-01-21 17:32

import django.db.models.deletion
import dnd.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0024_alter_character_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='my_origin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dnd.origin'),
        ),
        migrations.AlterField(
            model_name='character',
            name='protect_char_state',
            field=models.OneToOneField(default=dnd.models.ProtectStateModel.default_protect_state, on_delete=django.db.models.deletion.CASCADE, to='dnd.protectstatemodel'),
        ),
        migrations.AlterField(
            model_name='character',
            name='skill_char_state',
            field=models.OneToOneField(default=dnd.models.SkillStateModel.default_skill_state, on_delete=django.db.models.deletion.CASCADE, to='dnd.skillstatemodel'),
        ),
    ]
