# Generated by Django 5.1.4 on 2025-01-21 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0025_alter_character_my_origin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='protect_char_state',
            new_name='protect_state',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='skill_char_state',
            new_name='skill_state',
        ),
        migrations.RemoveField(
            model_name='character',
            name='my_origin',
        ),
        migrations.AddField(
            model_name='character',
            name='origin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dnd.origin'),
        ),
        migrations.AlterField(
            model_name='character',
            name='world_outlook',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dnd.worldoutlook'),
        ),
    ]
