# Generated by Django 5.1.4 on 2025-01-21 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0027_rename_origin_character_my_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='my_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dnd.origin'),
        ),
    ]
