# Generated by Django 5.1.4 on 2025-01-21 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0028_alter_character_my_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secondarymodel2',
            name='primary_model',
        ),
        migrations.RemoveField(
            model_name='secondarymodel3',
            name='primary_model',
        ),
        migrations.DeleteModel(
            name='SecondaryModel1',
        ),
        migrations.DeleteModel(
            name='SecondaryModel2',
        ),
        migrations.DeleteModel(
            name='SecondaryModel3',
        ),
    ]
