# Generated by Django 5.1.4 on 2025-01-21 18:12

import django.db.models.deletion
import dnd.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0029_remove_secondarymodel2_primary_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='background',
            field=models.OneToOneField(default=dnd.models.BackgroundModel.default_background_state, on_delete=django.db.models.deletion.CASCADE, to='dnd.backgroundmodel'),
        ),
    ]
