# Generated by Django 5.1.4 on 2025-01-21 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0030_alter_character_background'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='background',
            new_name='background2',
        ),
    ]
