# Generated by Django 5.1.4 on 2025-01-21 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0031_rename_background_character_background2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='background2',
            new_name='background',
        ),
    ]
